version: "3.7"

services:
  app:
    build: ./node
    command: npm start
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  vernemq:
    image: vernemq/vernemq
    restart: always
    links:
      - "mongo:database"
    ports:
      - "1883:1883"
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      #DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"

      # Authentication with MongoDB
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_MONGODB__ENABLED: "on"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__HOST: "database"
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PORT: 27017
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__LOGIN: vernemq
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PASSWORD: vernemq
      DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__DATABASE: devices
      

  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    